### PR TITLE
Simplify a while loop

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
When the `token.type !== 'paren'` condition is false, the `token.type === 'paren'` condition is true, so there is no need to check the `token.type === 'paren'` condition on the right side of the `||` operator.

### CODE REVIEW

**Comment by adarsh-why** [comment]
Good addition to the code. However I was thinking whether 
while ( token.value !== ')' ) 
will be sufficient or not?

**Comment by EvgenyOrekhov** [comment]
@adarsh-why I guess it will, but the point is to

> help you learn about how most compilers work

and most compilers would check the token type.

**Comment by adarsh-why** [comment]
@EvgenyOrekhov  .. Yes you are right. Thanks :)

**Comment by exetwezz** [comment]
Same as #34, though that's an issue.

**Comment by EvgenyOrekhov** [comment]
@exetwezz in #34 @thejameskyle rushed to his conclusion. The proposed change doesn't alter the semantics of the while condition. I added the description.

**Comment by EvgenyOrekhov** [comment]
Though now I'm thinking if it would be better to write the condition this way:
```javascript
while (
    !(token.type === 'paren' && token.value === ')')
)
```

**Pull request closed without merging**
