### PR TITLE
Add link to PHP version

### PR DESCRIPTION
**Pull request by BafS**
I have ported your code in PHP if you are interested. It would be nice to see some ports in other languages.

### CODE REVIEW

**Comment by brxf** [comment]
:+1:

**Comment by thejameskyle** [comment]
This program will look almost exactly the same across any imperative language just with slightly different syntaxes and APIs. If it makes people feel more comfortable (which I imagine it does) then that's awesome, but a line by line conversion isn't going to be natural for every language.

Also, thank you for licensing it as Creative Commons.

I can merge this, however I would prefer to centralize as much as possible so things can be updated when they need to, and I might be able to integrate it with the interactive tutorial site I'm building.

Would you mind opening a PR that adds this to the repository instead?

**Comment by thejameskyle** [comment]
Sorry clicked the wrong button

**Comment by BafS** [comment]
Yes sure ! So I add the php file directly in the main repository or in a folder ?

**Comment by thejameskyle** [comment]
Just add a `super-tiny-compiler.php` file at the root of the repo. I'll figure out if it needs to be better organized than that.

**Comment by thejameskyle** [comment]
Moving to #30

**Pull request closed without merging**
