### PR TITLE
updated LETTERS regex

### PR DESCRIPTION
**Pull request by sarbbottam**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you update the annotated file too?

**Comment by sarbbottam** [comment]
My bad, updated it. Thanks.

**Comment by sarbbottam** [comment]
Why do we need the `unannotated`? Sorry, I am repeating any concerns.

**Comment by thejameskyle** [comment]
Some people just wanted to see the code. *shrug*

**Comment by thejameskyle** [comment]
Thanks!

**Pull request merged**
